### ISSUE TITLE
Crash in world gen

### ISSUE THREAD

**Issue by mdsn** [thebracket/bgame#133]
```
MapIdx bounds check fail: 256/178/71
bgame: bgame/src/planet/builder/regions/../../indices.hpp:16: int mapidx(const int&, const int&, const int&): Assertion `x>-1 && x<REGION_WIDTH && y>-1 && y<REGION_HEIGHT && z>-1 && z<REGION_DEPTH' failed.
zsh: abort (core dumped)  ./bgame
```

**Comment by thebracket** [comment]
Thanks for the report; there's a couple of places that could have triggered that, I'll see what I can do.

**Comment by mdsn** [comment]
Thanks! If it's any help, world generation had already finished passing years, the screen said something about layers, and the last line on the console was something like "Built an Ant-Mound".

**Comment by thebracket** [comment]
I believe I've found the issue; I'll try and get a patch into the next build (which will be when I finish the AI revamp; it's only a few days away).
