### ISSUE TITLE
The build system tries to build an executable named png2rex but there's a directory named png2rex

### ISSUE THREAD

**Issue by Elronnd** [thebracket/bgame#19]
I'm not entirely sure what the original intent was here, but when I tried to build, ld complained at me because I was trying to make an executable called png2rex but there was already a directory called png2rex (which held the source files for said binary).  I worked around the problem by moving `png2rex/` to `png2rexx/`, and adjusting CMakeLists.txt accordingly, but is there any chance of an actual fix?

**Comment by thebracket** [comment]
It sounds like you're building from the root? I'd typically recommend doing an out-of-tree build (I always use a "build" folder off of the main - say `bgame/build`, and generate with `cmake -g"Unix Makefiles" ../src`). That would explain the naming collision.

With that said, I could safely remove png2rex from the build. It isn't currently used (it was, in an earlier version). I'm short on time tonight, but I'll take a proper look int he morning.

Thanks!

**Comment by Elronnd** [comment]
Ahh, right.  It's been a while since I built something from source (I used to build *everything* from source), so I'd forgot.
