### ISSUE TITLE
build errors spectacularly

### ISSUE THREAD

**Issue by Elronnd** [thebracket/bgame#20]
I tried to build the game, but after it got about halfway through, it spat out a bunch of errors.  [Here](http://lpaste.net/222785)'s a pastebin of the errors.  I'm on linux, and I get this with both gcc and clang.

**Comment by thebracket** [comment]
There is a git submodule in src/rltk. I'm not near a good net connection  (on mobile), but i think i remember the command is "git submodule init" to sync it? I'll update the build instructions first thing when I'm back on a PC.

**Comment by Elronnd** [comment]
I don't think it's that.  I was having some other build errors, so I cloned the repo manually (the only way I knew of getting submodules were cloning with --depth) into rltk, and that fixed it.  It looks like typeclashes  maybe?

**Comment by thebracket** [comment]
I just got in front of a Linux system, and it did fail to build pretty spectacularly. I'll create a branch and see what I can do to get this going properly. Thanks for the report - Linux has been a little neglected recently (mostly because my laptop with Linux on it is having issues), so it's definitely time to remedy that.

**Comment by thebracket** [comment]
I've merged in the branch, after testing on a couple of Ubuntu systems I had available here. I've tried to simplify the process a bit, and updated the README (and website) to show the process. I've pretty much got it down to clone the repo, enter the folder, run `./setup-unix-build.sh`, `cd build`, `make` and `./bgame` to play.

I'm not a huge fan of git submodules, but they get the job done - and until I find a better way to keep in lock-step with rltk, I'll stick to it!

The setup-unix-build.sh script:

1. Runs `git submodule init` to sync the URL of the currently-synced RLTK commit.
2. Runs `git submodule update` to clone that release.
3. Creates a build folder and enters it.
4. Sets up symlinks to `world_defs`, `assets` and `rex`.
5. Creates an empty `world` directory (this is where savegames live).
6. Instructs you to run `make` or `make -j4` to build the thing.

It worked ok on my Ubuntu laptop, and another Ubuntu-based server I have at work for test purposes. So I'll close this issue - but please feel free to re-open it if you still have troubles.
