### ISSUE TITLE
Website refers to LUA instead of Lua

### ISSUE THREAD

**Issue by 0joshuaolson1** [thebracket/bgame#21]
http://bracketproductions.com/index.php/blackfuture/

**Comment by thebracket** [comment]
Good catch. I only recently found out that Lua isn't an acronym (seems like a common mistake, but I've no idea where that came from!); I'll see about getting that fixed very soon.

Thanks!

**Comment by thebracket** [comment]
I _think_ I've caught all of the cases where I capitalized Lua inappropriately. WordPress is lacking a good regex search/replace (as far as I can tell - web dev isn't my strong suit). Thanks again!
